#!/bin/bash

# Copyright (C) 2014 The SaberMod Project
# This file is free software; The SaberMod Project
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

###########################################################################
###########################################################################
#####
#####  C O N F I G U R A T I O N
#####
###########################################################################
###########################################################################

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01';

# Try to parallelize the build for faster performance.
JOBS="$(cat /proc/cpuinfo | grep -c processor)";

# Determine Make flags
MAKE_FLAGS=-j"$JOBS";

# Build cloog and isl, files will be installed to /usr/local
cd ../cloog/cloog-0.18.3;
./configure --with-sysroot=/

# Build
sudo make $MAKE_FLAGS;

# Install
sudo make install;

# Clean local build
sudo make distclean;

cd ../../isl/isl-0.14;
./configure --with-sysroot=/

# Build
sudo make $MAKE_FLAGS;

# Install
sudo make install;

# Clean local build
sudo make distclean;

cd ../../build-scripts;
